### ISSUE TITLE
Importing Custom CSS with Tailwind classes does not work

### ISSUE THREAD

**Issue by bornResponsive** [codewithchu/tailwindcss-v2-setup-install#1]
Hi, I posted this on YouTube but just came across the GitHub so I'll post it here.

According to some of the members of the Tailwind Discord channel they say custom CSS with tailwind classes should work for example:

<img width="766" alt="Screenshot 2021-01-15 at 14 55 39" src="https://user-images.githubusercontent.com/4182478/105017581-dbac3b00-5a3b-11eb-99f7-ccf87870c323.png">

In my case the custom css is header.css and with following test tailwind classes:

`.header {
       @apply bg-black text-xl font-semibold;
}`

However the PostCSS does not pick this up. Only normal CSS works which is not what I want.
Here is my PostCSS config file:

<img width="295" alt="Screenshot 2021-01-18 at 15 23 13" src="https://user-images.githubusercontent.com/4182478/105017325-8b34dd80-5a3b-11eb-9934-e968133d9d37.png">

The official documentation seems to suggest it should work but it is vague:
https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports

Have you had this issue?

**Comment by bornResponsive** [comment]
**Update:**

Hi, thanks for the reply on  Youtube.

<img width="462" alt="Screenshot 2021-01-31 at 11 38 28" src="https://user-images.githubusercontent.com/4182478/106382837-0bebc600-63ba-11eb-9256-4d5806e81208.png">

What I had missed were 2 things:

1. changing @tailwind to @import 
2. I did not take into account postcss was only running at production with your code.


Thanks for the help everything is working now.

**Comment by codewithchu** [comment]
No Worries, glad it helped.

here's the solution I outlined from youtube comment so it's here for anyone to copy and paste.

There's a couple of things you would need to do. (I'm assuming you're using my source code or followed the video).
Install npm package postcss-import and add the postcss-import as plugin in your postcss.config.js above tailwind

Change in source css file
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
To 
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

Now my build script doesn't use postcss only the production npm script so you''ll need to modify that.
You can reference for some dos and don'ts when @importing your css.
https://tailwindcss.com/docs/using-with-preprocessors#using-post-css-as-your-preprocessor 

I'll close the issues.
